### PR TITLE
Prepare for odm 2.0

### PR DESCRIPTION
**Pull request by arendjantetteroo**
Also needs changes on doesntmatter/mongodb-migration: https://github.com/doesntmattr/mongodb-migrations/pull/41

### CODE REVIEW

**Comment by arendjantetteroo** [comment]
@caciobanu looks like some travis things need to change. Possibly the removal of ext-mongo vs ext-mongodb?

**Comment by caciobanu** [comment]
An issue I see now is that doesntmattr/mongodb-migrations doesn't get updated on packagist.

**Comment by arendjantetteroo** [comment]
did you add a new release for that already?

**Comment by caciobanu** [comment]
Just merged in master.

**Comment by arendjantetteroo** [comment]
from the packagist website : 

> Update Schedule
New packages will be crawled immediately after submission if you have JS enabled.

Existing packages without auto-updating (GitHub/BitBucket hook) will be crawled once a week for updates. When a hook is enabled packages are crawled whenever you push, or at least once a month in case the crawl failed. You can also trigger a manual update on your package page if you are logged-in as a maintainer.

It is highly recommended to set up the GitHub/BitBucket service hook for all your packages. This reduces the load on our side, and ensures your package is updated almost instantly. Check the how-to below.

The search index is updated every five minutes. It will index (or reindex) any package that has been crawled since the last time the search indexer ran.

**Comment by caciobanu** [comment]
There should be a hook but I think we need @redthor to check it.

**Comment by smoench** [comment]
`doesntmattr/mongodb-migrations` got a new release tag + [packagist](https://packagist.org/packages/doesntmattr/mongodb-migrations) also got updated.

Can we get this done? I'm happy to help :)

**Comment by arendjantetteroo** [comment]
@smoench feel free to add whatever is needed to get this done.

**Comment by arendjantetteroo** [comment]
@caciobanu can we get this merged or is there something still needed?

**Comment by arendjantetteroo** [comment]
@smoench i don't see the new release here https://github.com/doesntmattr/mongodb-migrations/releases ? where did you see it released?

**Comment by caciobanu** [comment]
I'm getting this in and also some other PR's. I hope I'll have time this week to check everything and write an upgrade file if needed and release a new version.

**Comment by arendjantetteroo** [comment]
@caciobanu the only change i needed to make was renaming the namespace from \Doctrine\Mongodb\Database to \Mongodb\Database in my migration files. 

Everything else still worked with regards to migration.

Thanks for merging.

**Pull request merged**
