### PR TITLE
fix requirements + fix symfony 5 compatibility

### PR DESCRIPTION
**Pull request by smoench**
waits for https://github.com/doesntmattr/mongodb-migrations/pull/49

### CODE REVIEW

**Comment by caciobanu** [comment]
For doesntmattr/mongodb-migrations I think the new version will be 3.0 as there are some braking changes.

**Comment by caciobanu** [comment]
This bundle will more likely get a 3.0 release.

**Comment by Eimantas123** [comment]
when it will be merged to support symfony 5?

**Comment by smoench** [comment]
@Eimantas123 once doesntmattr/mongodb-migrations gets a 3.0 tag I can increase the requirement in this PR and it would be mergeable

**Comment by jShox** [comment]
very waiting for 3.0

**Comment by Perni1984** [comment]
ping @caciobanu - is there something we can do to facilitate the 3.0 release? Willing to spend some time here, as an upgraded package would be very much helpful for a current project of ours.

**Comment by caciobanu** [comment]
I will get it out this weekend as I'll have some spare time.

**Comment by caciobanu** [comment]
@smoench @Eimantas123 @jShox @Perni1984: Version **3.0** is out.

**Comment by smoench** [comment]
Thank you @caciobanu!

**Pull request merged**
