### PR TITLE
Rename AntiMatterCommand to CommandHelper and remove extends

### PR DESCRIPTION
**Pull request by redthor**

### CODE REVIEW

**Comment by caciobanu** [comment]
Looking good to me.

**Comment by redthor** [comment]
Sorry @caciobanu 
I made an error with this PR. It was supposed to target the `2.0` branch from my feature branch. Not merge into master.

So I've fixed it up:
1. reverted the change in `master`
2. created `2.0.0-dev` and merged it into that branch

It is a breaking change if someone is using that class.

**Comment by caciobanu** [comment]
We should follow an workflow as all the other projects where master is for DEV. If we are going to support more versions than the latest then we should have a version branch (In our case that should be 1.1).

@redthor @trq do you agree on the workflow ? Also should we offer support only for the latest version or let's say last 2 versions ?

2 versions supported:
- 1.1 - current release and stable version
- master - dev and future 2.0 (or 1.2 or smth else) release

1 version and always the newest version supported:
- master - dev

**My suggestion is to offer support only for the latest version for now.**

**Comment by redthor** [comment]
Hi @caciobanu 
I'm not too sure... I guess, you are right, we should do the same thing as other projects.

Does it mean we must must now create `1.1.x-dev` from master (before merging anything) so we can bug fix `1.1`?

Do you know what this (in `composer.json`) is doing for us?
`    "extra": {
        "branch-alias": {
            "dev-master": "1.0.x-dev"
        }
},`

thanks :)

**Comment by caciobanu** [comment]
We can created just 1.1 from current master so we can offer fixes for 1.1 version until we have a 2.0 release, as we know that is the DEV branch for 1.1.x releases. This is the flow that Symfony and Doctrine follows.

That extra tells Packagist to create an alias for **dev-master** named **1.0.x-dev**. You can check that here: https://packagist.org/packages/doesntmattr/mongodb-migrations-bundle.

**Comment by redthor** [comment]
Ok, thanks. I've created branch `1.1` and re-applied this PR to `master`

**Pull request merged**
